### ISSUE TITLE
GitHub Actions: Can't pull docker images

### ISSUE THREAD

**Issue by thetredev** [thetredev/voidlinux-repository#2]
https://github.com/xdeb-org/voidlinux-repository/actions/runs/6683994344/job/18160793849 for example. Might affect all other repositories too. Need to look into how GitHub handles package permissions for organizations.

**Comment by thetredev** [comment]
Found the issue: https://github.com/orgs/xdeb-org/packages - these packages are marked `private`. They were `public` when the repositories were owned by me. Running jobs inside containers directly works (see https://github.com/xdeb-org/xdeb-install/actions), but I'm running containers manually in this repository here via `docker run` because I only need them temporarily.

@toluschr what do you think? Make them public (https://docs.github.com/en/enterprise-server@3.8/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility) or login via GHCR Login action during CI?

By the way, https://github.com/xdeb-org/xdeb-install/pkgs/container/xdeb-install/142184923?tag=devcontainer needs to be public at all times, because we need that container image locally for development and testing. All the others can optionally be public.

**Comment by toluschr** [comment]
The CI stuff is beyond my knowledge. Just make them public I guess. Do you have permission to do that?

**Comment by thetredev** [comment]
Sadly not. I can't manage organization permissions.

**Comment by toluschr** [comment]
I did not know that being an organization-wide administrator will not give you full permission over your own repositories. Anyways, I changed the policy on that and it should now work.

**Comment by thetredev** [comment]
Yeah it's strange. I don't see the organization settings button at all :( 

Thanks!

**Comment by thetredev** [comment]
Omg I'm stupid lol. Well, half at least. The policy you changed is for any future uploads, while I could change settings for single packages. I just didn't see that the button was available for me under specific packages. Sorry for the inconvenience.

Closing the issue.
