### ISSUE TITLE
What is the licence of this project?

### ISSUE THREAD

**Issue by kytta** [thetredev/voidlinux-repository#8]
Hello there,

I've just discovered this repo, and I like the setup and would like to adopt it for myself. I'd like to just copy most of your code, but your repo does not have a licence, so I can't just assume it's open-source.

Would you be okay with me adopting the files of the project and sublicencing those (including my changes) under BSD-2-Clause?

No matter the answer, it would also be beneficial for me and others if you would name an explicit licence these files are available under :)

**Comment by thetredev** [comment]
That's a good question. I just read through BSD-2 and it seems like a good fit. I'll update the repo ASAP.

**Comment by thetredev** [comment]
Fixed with 9d522bb521d77dfeaf3e6b94d0f98bb61d3bffd1. I's BSD-2 now :)

Closing.
